- src/mayastorpool_schema/mayastorpool_schema_test.go
JIRA: https://mayadata.atlassian.net/browse/MQ-2512
> fix: refactor mayastor pool schema test to wait for all pools to be deleted

- src/common/k8sinstall/util.go
- src/common/k8stest/util.go
JIRA: https://mayadata.atlassian.net/browse/MQ-2513
> chore: verify mayastor node status after installation before pool creation steps

- src/common/k8stest/util_node.go
- src/nexus_location/nexus_location_test.go
> fix nexus_location test

- src/nexus_location/nexus_location_test.go
Make deferredAsserts handling consistent for all test
cases.
Add a few useful log statements to aid analysis
> chore: minor tweaks to nexus location test

- src/common/controlplane/v1/msn_cp.go
- src/common/controlplane/v1/msp_cp.go
- src/common/controlplane/v1/msv_cp.go
- src/common/k8stest/msv.go
With VPN access kubectl-mayastor just works if KUBECONFIG is
set up correctly.
This simplifies the control plane code interfacing with the restful
control-plane.
Rip out most of the offending bits.
But retain the use of IP addresses, to communicate with the
restful control plane for replica information.
Uses master node IP addresses now instead of worker nodes,
this will change when MQ-2319 is merged.
> chore: stop using node urls with kubectl-mayastor MQ-2537

- src/node_failure/node_failure_test.go
- keep on retrying list nodes until it succeeds.
- Update logs
- Fill the node list only once
> Fix node failure tests

- src/stale_msp_after_node_power_failure/stale_msp_after_node_power_failure_test.go
- after applying the node selectori
- pause for 1 min to allow the pods to migrate
- ascertain that migration was successful by readiness check
- migrate the csi-controller
- strictly speaking this isn't required but mimics moac deployment
> chore: fixes for stale_msp_after_node_power_failure_test

- src/common/k8stest/util_events.go
- src/primitive_fuzz_msv/config.go
- src/primitive_fuzz_msv/util.go
Verify pvc creation errors out instead of deploying the app and verifying its status.
> fix primitive fuzz msv

- src/MQ-1783-fsx_ext4_stress/util.go
- src/common/mayastorclient/nexus.go
Fix copy and paste error
ListPools -> ListNexuses
> fix: use correct text when loggin messages

- src/MQ-1783-fsx_ext4_stress/util.go
In case of restful control plane , when a replica is faulted via gRPC corresponding new replica created on the same pool with Degraded state before transitioning to Online state. So add degraded replica state check to wait for single Faulted or Degraded replica state.
JIRA: https://mayadata.atlassian.net/browse/MQ-2597
> update(fsx_ext4_stress_test): verify for degraded state of faulted replica

- src/common/k8sinstall/util.go
> increase log level to debug in mayastor control plane components

- src/MQ-1498-primitive_device_retirement/primitive_device_retirement_test.go
- src/common/k8stest/util_cleanup.go
> Increase wait time for rebooted node to settle down

- src/MQ-2632-pvc_create_delete/config.go
- src/MQ-2632-pvc_create_delete/pvc_create_delete_test.go
- src/MQ-2632-pvc_create_delete/util.go
- src/common/e2e_config/e2e_config.go
- src/common/k8stest/msv.go
JIRA: https://mayadata.atlassian.net/browse/MQ-2632
> test(e2e): test to verify large number of pvc create and delete operation

- scripts/test_lists.sh
- src/MQ-2307-etcd_inaccessibility/config.go
- src/MQ-2307-etcd_inaccessibility/etcd_inaccessibility_test.go
- src/MQ-2307-etcd_inaccessibility/utils.go
- src/common/k8stest/mayastor_check.go
- src/common/k8stest/test.go
- src/common/k8stest/util_pod.go
- src/node_failure/node_failure_test.go
- src/node_shutdown/config.go
- src/node_shutdown/node_shutdown_test.go
- src/single_msn_shutdown/config.go
- src/single_msn_shutdown/core_agent.go
- src/single_msn_shutdown/single_msn_shutdown_test.go
- src/single_msn_shutdown/utils.go
- src/stale_msp_after_node_power_failure/config.go
- src/stale_msp_after_node_power_failure/stale_msp_after_node_power_failure_test.go
Signed-off-by: w3aman <aman.gupta@mayadata.io>
> test(e2e): add tests to verify data ptotection when etcd is inaccessible MQ-2307

- src/MQ-2307-etcd_inaccessibility/etcd_inaccessibility_test.go
- src/common/k8sinstall/util.go
- src/common/k8stest/util.go
- src/common/k8stest/util_e2e_agent.go
- src/common/k8stest/util_testpods.go
- src/control_plane_rescheduling/control_plane_resheduling_test.go
- src/mayastorpool_schema/mayastorpool_schema_test.go
- src/primitive_msp_deletion/primitive_msp_deletion_test.go
- src/primitive_replicas/primitive_replicas_test.go
- src/single_msn_shutdown/config.go
- src/single_msn_shutdown/core_agent.go
- src/stale_msp_after_node_power_failure/config.go
- src/stale_msp_after_node_power_failure/stale_msp_after_node_power_failure_test.go
JIRA: https://mayadata.atlassian.net/browse/MQ-2747
> refactor: remove assert from common code (src/comon/k8stest/util.go)

- src/common/k8stest/util_pvc.go
- use correct string for PV id when checking PV
- fix scoping for err variables
> fix: incorrect checking in MkPVC

- scripts/test_lists.sh
- src/MQ-2644-invalid_volume_sizes/config.go
- src/MQ-2644-invalid_volume_sizes/invalid_volume_sizes_test.go
- src/MQ-2644-invalid_volume_sizes/utils.go
I have issue with test 2 and 3. I can't find out what is wrong. Clean up job can't delete PVC
> test(e2e) MQ-2644 invalid volume sizes

- src/MQ-2219-rc-reconciliation/utils.go
- src/MQ-2307-etcd_inaccessibility/etcd_inaccessibility_test.go
- src/MQ-2330-ms_pod_disruption_rm_vol/replica_pod_remove_rm_vol_test.go
- src/common/constants.go
- src/common/k8sinstall/util.go
- src/common/k8stest/mayastor_check.go
- src/common/k8stest/util_e2e_agent.go
- src/common/k8stest/util_node.go
- src/common/k8stest/util_pod.go
- src/common/locations/util_locations.go
- src/io_soak/io_soak_test.go
- src/ms_pod_disruption/ms_pod_disruption_test.go
- src/ms_pod_disruption_no_io/replica_copy_test.go
- src/ms_pod_disruption_rm_msv/replica_pod_remove_rm_msv_test.go
- src/nexus_location/nexus_location_test.go
- src/node_failure/node_failure_test.go
- src/node_shutdown/node_shutdown_test.go
- src/node_shutdown/utils.go
- src/primitive_msp_deletion/primitive_msp_deletion_test.go
- src/pvc_delete/pvc_delete_test.go
- src/single_msn_shutdown/core_agent.go
- src/single_msn_shutdown/single_msn_shutdown_test.go
- src/single_msn_shutdown/utils.go
- src/stale_msp_after_node_power_failure/stale_msp_after_node_power_failure_test.go
JIRA: https://mayadata.atlassian.net/browse/MQ-2760
> refactor: remove assert from node label and unlabel functions

- src/common/k8stest/util_pvc.go
1 - change to test and then sleep
2 - reduce sleep time to 1 second
Reduced MkPVC call duration from circa 30 seconds to 2-3 seconds
which has a major impact on tests creating large number of volumes
synchronously
> fix: tune timeouts in MkPVC and RmPVC

- pipelines/Mayastor-bolt-pipeline/Jenkinsfile
- pipelines/bolt/on_demand/Jenkinsfile
- pipelines/common/common.groovy
Bolt build and test pipeline using smoke-test.
Packaging stage not yet implemented.
Removed some deprecated functions.
> test(e2e) er1-163

- src/tools/extended-test-framework/test_director/connectors/xray/test_execution.go
- src/tools/extended-test-framework/test_director/connectors/xray/test_plan.go
- src/tools/extended-test-framework/test_director/connectors/xray/test_run.go
- src/tools/extended-test-framework/test_director/connectors/xray/xray.go
- src/tools/extended-test-framework/test_director/handlers/events_cache.go
- src/tools/extended-test-framework/test_director/handlers/test_runs.go
Improvement to ETFW error handling so that test director issues are reported in its log and can propagate to error responses to rest requests.
> test(etfw) test director hardening

- configurations/testlists.yaml
- scripts/e2e-test.sh
- scripts/testlists.py
use testlists.py and configurations/testlists.yaml in
e2e-test.sh
Create a list of tests that are known to pass
profile name is passing
> fix: use testlists in a consistent manner
