- src/primitive_msp_state/util.go
The latency on pool CRs state updates is higher
than with MOAC and so the primitive msp state
test is "failing".
Refactor the primitive msp state test to workaround
this change in behaviour
- add retries
- timeouts
> refactor: workaround to allow retries for msp checks

- src/common/k8stest/util_testpods.go
Use time dependency instead of name changes to
check if pods have been restarted.
This allows us to restart and check pods belonging
to deamonsets, deployments and statefulsets
> chore: fix restart logic

- configurations/hcloudci_config.yaml
- configurations/selfci_config.yaml
- src/common/custom_resources/util.go
- src/common/e2e_config/e2e_config.go
- src/common/k8stest/test.go
- src/common/k8stest/util.go
- src/common/k8stest/util_cleanup.go
- src/common/types.go
Add a configuration item "beforeEachCheckAndRestart" to enable
restarts in the BeforeEachCheck function.
Currently if an 'It' clause of test fails and leaves
resources, the cluster is considered unusable because
of indeterminate state.
Setting beforeEachCheckRestart changes the behaviour such
that mayastor is restarted if
- If prior ResourceCheck has failed
- ResourceCheck fails
The 2nd behaviour may help for selfci runs.
Add a configuration item "failQuick" to ease debugging and
development of tests.
When trying to determine reasons for failure, developers
prefer fast fail.
fail quick doesn't quite manage that, it only affects the i
behaviour of the generic BeforeEachCheck and AfterEachCheck functions.
ResourceCheck errors are stored persistently and if fail quick
is enabled both …
> chore: refactor to aid test coverage and development

- src/common/k8stest/util.go
A test hung in WaitPodComplete but the level of logging
is insufficient to yield clues.
Rectify this.
> chore: tweak logging in k8stest.WaitPodComplete

- src/MQ-1783-fsx_ext4_stress/config.go
- src/MQ-1783-fsx_ext4_stress/fsx_ext4_stress_test.go
- src/MQ-1783-fsx_ext4_stress/util.go
When verifying pod state sample pod running state,
and act accordingly.
Tweak sleep times to generate fewer repeated messages.
> chore: fix pod running or complete check

- src/pvc_delete/pvc_delete_test.go
replaced a 120s timeout with a 600s timeout.
add log statements so that it is clearer what
is being checked and hence is clearer why a
failure has occurred.
> chore: pvc_delete: increase timeout

- src/common/k8stest/util_testpods.go
In CheckPodContainerCompleted avoid null pointer access
of field pod.Status.ContainerStatuses[n].State.Terminated
This also means that CheckPodComplete can be invoked,
without checking for prior transition to running state.
> fix: k8stest.CheckPodComplete: null pointer check

- src/MQ-1498-primitive_device_retirement/primitive_device_retirement_test.go
- src/MQ-1498-primitive_device_retirement/utils.go
Primitive device retirement only contained tests to detach/crash volume/pods native to nexus. This PR adds disruption for remote volume/pods also.
> update(device-retirement-test): add tests to detach/crash non-nexus volume/pod

- src/common/e2e_config/e2e_config.go
- src/ms_pod_disruption/fault_replica_device_test.go
- src/ms_pod_disruption/ms_pod_disruption_test.go
Modify the ms_pod_disruption test so that replicas can be faulted by offlining the corresponding backing device using the e2e-agent.
There are now two "It" clauses in this test
* the original functionality (disabled by default) which suppresses replica pods but uses grpc to fault the nexus replica
* the new version (enabled by default) which offlines the backing device for each replica.
The single source file is now three files, one each for the body of the two tests and the third which is the entry point and contains library code for both tests.
> test(e2e): MQ-2598 fault replica device to remove replicas

- src/primitive_fault_injection/config.go
- src/primitive_fault_injection/util.go
Some times faulted replica takes time to recreate itself on same pool, so to avoid test failure due to this below changes are done:
- Add eventually loop to wait for faulted replica to removed and check for replicas state as degraded and online state.
- Increase default time out value to 240 seconds
> fix(fault_injection_test):  timeout to wait for replicas to be in degraded or online state

- src/nexus_location/nexus_location_test.go
After checking whether a pod is provisioned,
sleep for 1 minute and then delete the pod,
this stops the test failing on k8s 1.22 and k8s 1.23.
Ostensibly the test fails because pvc deletion does not
complete successfully, however the root cause is that
the pod using the pvc is not deleted.
Adding the delay lets k8s complete the deletion of the pod,
and naturally pvc deletion will then complete.
> fix: tweak nexus_location test

- src/common/k8stest/test.go
- src/common/k8stest/util_testpods.go
RestartMayastorPods() func is useful in removing the restart count on the mayastor pods once the disruptive test has been completed. This is done to prepare stage for the next test.
Previously we were taking the restart count just at the beginning of the restart function. This was sometimes giving wrong numbers as the test might leave the cluster in any state. At some instances there were 2 pods in the list for the same deployment, one in running and the other in terminating/pending/....
In this PR, we are taking the mayastor pod count for comparision purposes just at the beginning of the test. 
> fix(RestartMayastorPods): verify restart with the mayastor pod count before tests begin

- src/MQ-2307-etcd_inaccessibility/etcd_inaccessibility_test.go
- src/MQ-2307-etcd_inaccessibility/utils.go
- src/common/k8stest/util.go
- src/node_failure/node_failure_test.go
- src/node_shutdown/utils.go
- src/primitive_msp_deletion/primitive_msp_deletion_test.go
- src/single_msn_shutdown/utils.go
This PR limits the etcd inaccessibility test to complete as soon as its intent is met instead of fixing or checking for the broken pieces.
> fix etcd-inaccessibility tests

- src/common/e2e-agent/client.go
e2e-agent client code was not checking the http
response code after making the rest call.
Return an error if the code is anything other than 200.
> test(e2e): e2e-agent client status code check

- pipelines/Mayastor-e2e-etfw-cluster-builder/Jenkinsfile
This matches the default node type used by the ginkgo tests.
> test(etfw): change default node type to cpx31

- scripts/runtest.sh
- src/common/e2e_config/e2e_config.go
Add scripts/runtest.sh this
- allows us to test the fix
- simplifies running tests manually
> fix: Remove dependency of common functions on ginkgo e2e-test config

- src/primitive_msp_deletion/primitive_msp_deletion_test.go
Verify node status online before creating pool.
If node is not online and a pool creation is tried, msp might get into error state.
> fix primitive_msp_deletion test

- src/tools/extended-test-framework/log_monitor/scripts/build.sh
- src/tools/extended-test-framework/log_monitor/scripts/build_img.sh
- src/tools/extended-test-framework/scripts/build.sh
- src/tools/extended-test-framework/test_conductor/scripts/build.sh
- src/tools/extended-test-framework/test_director/scripts/build.sh
- src/tools/extended-test-framework/test_director/scripts/build_img.sh
- src/tools/extended-test-framework/workload_monitor/scripts/build.sh
- src/tools/extended-test-framework/workload_monitor/scripts/build_img.sh
Allow the docker image tag to be parameterised in the build scripts.
This makes it easier to develop new tests without impacting the
working images which typically use "latest".
TODO, update the deployment script to be parameterised as well.
> test(etfw): specify image tags

- src/tools/extended-test-framework/deploy/test_conductor/primitive_pool_deletion/config.yaml
- src/tools/extended-test-framework/test_conductor/tests/primitive_pool_deletion.go
Add the XRay test for the primitive_pool_deletion test
to the config.
Also do not configure the workload_monitor to monitor
mayastor pods because these are forced to restart by the test,
otherwise the test will always fail.
> test(etfw): add XRay test to config for pool test

- src/tools/extended-test-framework/deploy/test_conductor/replica_elimination/config.yaml
- src/tools/extended-test-framework/test_conductor/tc/config.go
- src/tools/extended-test-framework/test_conductor/tc/workload_monitor_lib.go
- src/tools/extended-test-framework/test_conductor/tests/replica_elimination.go
- src/tools/extended-test-framework/test_conductor/tests/test_common.go
- tools/e2e-storage-tester/e2e-storage-tester.c
Extend the replica elimination test to test for replicas
by killing the mayastor processes on all nodes.
A volume with no replicas, or with all replicas faulted
is no longer considered a test failure.
Add option to run e2e-storage-tester for a given duration.
Allow test-conductor to exclude pods from workload-monitor
checking via app label.
Reduce volume sizes to speed up test.
> test(etfw): replica test via killing mayastor pods

- pipelines/Mayastor-e2e-selfci-image-builder/Jenkinsfile
- pipelines/common2/common.groovy
- pipelines/generic-system-test/Jenkinsfile
- scripts/create-install-image.sh
- scripts/e2e-test.sh
- scripts/extract-install-image.sh
- scripts/re-tag-images.sh
Create install-images for bolt in the registry under datacore/
Fix the fallout from that change.
Make re-tag-images more portable.
As a bonus this should just work correctly with older images
which have different image names
> refactor: handle images for mayastor and bolt
